# Site settings
title:          Dan Blundell
description:    "Tech Lead"
url:            "https://www.danblundell.com"
timezone:       Europe/London
# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X

# Author
author:
  name:         Dan Blundell
  url:          https://www.danblundell.com
  email:        hello@danblundell.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
